news/urls.py
from django.urls import path

from .views import (
    index,
    UserCreateView,
    TopicListView,
    TopicCreateView,
    TopicUpdateView,
    TopicDeleteView,
    RedactorListView,
    RedactorDetailView,
    RedactorCreateView,
    RedactorUpdateView,
    RedactorDeleteView,
    NewspaperListView,
    NewspaperDetailView,
    NewspaperCreateView,
    NewspaperUpdateView,
    NewspaperDeleteView
)

urlpatterns = [
    path("", index, name="index"),
    path("register_user/", UserCreateView.as_view(), name="register_user"),
    path(
        "topics/",
        TopicListView.as_view(),
        name="topic-list",
    ),
    path(
        "topics/create/",
        TopicCreateView.as_view(),
        name="topic-create"
    ),
    path(
        "topics/<int:pk>/update/",
        TopicUpdateView.as_view(),
        name="topic-update"
    ),
    path(
        "topics/<int:pk>/delete/",
        TopicDeleteView.as_view(),
        name="topic-delete"
    ),
    path(
        "redactors/",
        RedactorListView.as_view(),
        name="redactor-list"
    ),
    path(
        "redactors/<int:pk>/",
        RedactorDetailView.as_view(),
        name="redactor-detail"
    ),
    path(
        "redactors/create/",
        RedactorCreateView.as_view(),
        name="redactor-create"
    ),
    path(
        "redactors/<int:pk>/update/",
        RedactorUpdateView.as_view(),
        name="redactor-update"
    ),
    path(
        "redactors/<int:pk>/delete",
        RedactorDeleteView.as_view(),
        name="redactor-delete"
    ),
    path(
        "newspapers/",
        NewspaperListView.as_view(),
        name="newspaper-list"
    ),
    path(
        "newspapers/<int:pk>/",
        NewspaperDetailView.as_view(),
        name="newspaper-detail"
    ),
    path(
        "newspapers/create",
        NewspaperCreateView.as_view(),
        name="newspaper-create"
    ),
    path(
        "newspaper/<int:pk>/update/",
        NewspaperUpdateView.as_view(),
        name="newspaper-update"
    ),
    path(
        "newspaper/<int:pk>/delete/",
        NewspaperDeleteView.as_view(),
        name="newspaper-delete"
    ),
]

app_name = "news"

newspaper_agency/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("news.urls", namespace="news")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

news/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Topic(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["id"]

    def __str__(self):
        return self.name


class Redactor(AbstractUser):
    year_of_experience = models.IntegerField(null=True)

    class Meta:
        verbose_name = "redactor"
        verbose_name_plural = "redactors"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Newspaper(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    published_date = models.DateField()
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    redactors = models.ManyToManyField(Redactor, related_name="newspapers")

    def __str__(self):
        return self.title

news/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from news.models import Redactor, Newspaper


class UserCreateForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + ("email", "first_name", "last_name", "year_of_experience")


class TopicSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name..."})
    )


class RedactorSearchForm(forms.Form):
    year_of_experience = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by year_of_experience.."})
    )


class RedactorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Redactor
        fields = UserCreationForm.Meta.fields + (
            "first_name", "last_name", "year_of_experience"
        )


class RedactorUpdateForm(forms.ModelForm):
    class Meta:
        model = Redactor
        fields = ["username", "first_name", "last_name",
                  "email", "password", "is_active", "year_of_experience"]


class NewspaperSearchForm(forms.Form):
    title = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by title.."})
    )


class NewspaperForm(forms.ModelForm):
    published_date = forms.DateField(widget=forms.DateInput(attrs={'type': 'date'}))
    redactors = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Newspaper
        fields = "__all__"

news/views.py
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User

from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from news.forms import TopicSearchForm, NewspaperSearchForm, RedactorCreationForm, RedactorUpdateForm, NewspaperForm, \
    UserCreateForm, RedactorSearchForm
from news.models import Topic, Redactor, Newspaper


@login_required
def index(request):
    """View function for the home page of the site."""

    num_newspapers = Newspaper.objects.count()
    num_redactors = Redactor.objects.count()
    num_topics = Topic.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_newspapers": num_newspapers,
        "num_redactors": num_redactors,
        "num_topics": num_topics,
        "num_visits": num_visits + 1,
    }

    return render(request, "news/index.html", context=context)


class UserCreateView(generic.CreateView):
    model = Redactor
    form_class = UserCreateForm
    template_name = "registration/register_user.html"
    success_url = reverse_lazy("news:index")


class TopicListView(LoginRequiredMixin, generic.ListView):
    model = Topic
    context_object_name = "topic_list"
    template_name = "news/topic_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TopicListView, self).get_context_data(**kwargs)

        name = self.request.GET.get("name", "")

        context["search_form"] = TopicSearchForm(initial={"name": name})

        return context

    def get_queryset(self):
        queryset = Topic.objects.all()

        form = TopicSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])

        return queryset


class TopicCreateView(LoginRequiredMixin, generic.CreateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("news:topic-list")


class TopicUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Topic
    fields = "__all__"
    success_url = reverse_lazy("news:topic-list")


class TopicDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Topic
    success_url = reverse_lazy("news:topic-list")


class RedactorListView(LoginRequiredMixin, generic.ListView):
    model = Redactor
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(RedactorListView, self).get_context_data(**kwargs)

        year_of_experience = self.request.GET.get("year_of_experience", "")

        context["search_form"] = RedactorSearchForm(initial={"year_of_experience": year_of_experience})

        return context

    def get_queryset(self):
        queryset = Redactor.objects.all()

        form = RedactorSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(year_of_experience__icontains=form.cleaned_data["year_of_experience"])

        return queryset


class RedactorDetailView(LoginRequiredMixin, generic.DetailView):
    model = Redactor
    queryset = Redactor.objects.all().prefetch_related("newspapers__topic")


class RedactorCreateView(LoginRequiredMixin, generic.CreateView):
    model = Redactor
    form_class = RedactorCreationForm
    success_url = reverse_lazy("news:redactor-list")


class RedactorUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Redactor
    form_class = RedactorUpdateForm
    success_url = reverse_lazy("news:redactor-list")


class RedactorDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Redactor
    template_name = "news/redactor_confirm_delete.html"
    success_url = reverse_lazy("news:redactor-list")


class NewspaperListView(LoginRequiredMixin, generic.ListView):
    model = Newspaper
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(NewspaperListView, self).get_context_data(**kwargs)

        title = self.request.GET.get("title", "")

        context["search_form"] = NewspaperSearchForm(initial={"title": title})

        return context

    def get_queryset(self):
        queryset = Newspaper.objects.all()

        form = NewspaperSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(title__icontains=form.cleaned_data["title"])

        return queryset


class NewspaperDetailView(LoginRequiredMixin, generic.DetailView):
    model = Newspaper


class NewspaperCreateView(LoginRequiredMixin, generic.CreateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("news:newspaper-list")


class NewspaperUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Newspaper
    form_class = NewspaperForm
    success_url = reverse_lazy("news:newspaper-list")


class NewspaperDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Newspaper
    success_url = reverse_lazy("news:newspaper-list")

templates/news/index.html
{% extends "base.html" %}

{% block content %}
    <h1> Newspaper agency Home</h1>
    <p>Welcome to the best news Ever!</p>
    <h2>Dynamic content</h2>
    <p>Newspaper record counts:</p>
    <ul>
        <li><strong>Newspaper:</strong> {{ num_newspapers }}</li>
        <li><strong>Redactors:</strong> {{ num_redactors }}</li>
        <li><strong>Topics:</strong> {{ num_topics }}</li>
    </ul>

    <p>You have visited this page
        {{ num_visits }} time{{ num_visits|pluralize }}.
    </p>

{% endblock %}

templates/news/newspaper_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete newspaper?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'news:newspaper-detail' pk=newspaper.id %}" class="btn btn-secondary">Cansel</a>
  </form>
{% endblock %}

templates/news/newspaper_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    {{ newspaper.title }}
  </h1>
  <a href="{% url 'news:newspaper-update' pk=newspaper.id %}" class="btn btn-secondary link-to-page">
    Update
  </a>

  <a href="{% url 'news:newspaper-delete' pk=newspaper.id %}" class="btn btn-danger link-to-page">
    Delete
  </a>
  <p>Topic: ({{ newspaper.topic.name }})</p>

  {% csrf_token %}
  {% if user in newspaper.redactors.all %}
    <a href="{% url 'news:newspaper-update' pk=newspaper.id %}" class="btn btn-danger link-to-page">
      Delete me from this newspaper
    </a>
  {% else %}
    <a href="{% url 'news:newspaper-update' pk=newspaper.id %}" class="btn btn-success link-to-page">
      Assign me to this newspaper
    </a>
  {% endif %}

  <h1>Redactor</h1>
  <hr>
  <ul>
    {% for redactor in newspaper.redactors.all %}
      <li>{{ redactor.username }} ({{ redactor.first_name }} {{ redactor.last_name }}; {{ newspaper.published_date }})</li>
      <p>{{ newspaper.content }}</p>
    {% endfor %}
  </ul>
{% endblock %}

templates/news/newspaper_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} newspaper</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/news/newspaper_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Newspaper list
    <a href="{% url 'news:newspaper-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" value="Submit" class="btn btn-secondary">
  </form>

  {% if newspaper_list %}
    <ol>
      {% for newspaper in newspaper_list %}
        <li>
          <a href="{% url "news:newspaper-detail" pk=newspaper.id %}">{{ newspaper.title }}</a>
          ({{ newspaper.topic.name }})
        </li>
      {% endfor %}
    </ol>
  {% else %}
    <p>There are no newspapers in base</p>
  {% endif %}
{% endblock %}

templates/news/redactor_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete redactor?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'news:redactor-detail' pk=redactor.id %}" class="btn btn-secondary">Cansel</a>
  </form>
{% endblock %}

templates/news/redactor_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ redactor.username }}
    <a href="{% url 'news:redactor-update' pk=redactor.id %}" class="btn btn-secondary link-to-page">
      Update user information
    </a>
    <a href="{% url 'news:redactor-delete' pk=redactor.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>
  </h1>

  <p><strong>First name:</strong> {{ redactor.first_name }}</p>
  <p><strong>Last name:</strong> {{ redactor.last_name }}</p>
  <p><strong>Year of experience:</strong> {{ redactor.year_of_experience }}</p>
  <p><strong>Is staff:</strong> {{ redactor.is_staff }}</p>

  <div class="ml-3">
    <h4>Newspaper</h4>

    {% for newspaper in redactor.newspapers.all %}
      <hr>
      <p><strong>Title:</strong> {{ newspaper.title }}</p>
      <p><strong>Topic:</strong> {{ newspaper.topic.name }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ newspaper.id }}</p>

    {% empty %}
      <p>No newspapers!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/news/redactor_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create redactor</h1>

  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/news/redactor_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Redactor list
    <a style="float: right" href="{% url 'news:redactor-create' %}">+</a>
  </h1>

  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" value="Submit" class="btn btn-secondary">
  </form>

  {% if redactor_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Year of Experience</th>
      </tr>
      {% for redactor in redactor_list %}
        <tr>
          <td>{{ redactor.id }}</td>
          <td><a href="{% url "news:redactor-detail" pk=redactor.id %}">{{ redactor.username }}
            {% if user == redactor %} (Me){% endif %}</a>
          </td>
          <td>{{ redactor.first_name }}</td>
          <td>{{ redactor.last_name }}</td>
          <td>{{ redactor.year_of_experience }}</td>
        </tr>
      {% endfor %}

    </table>
  {% else %}
    <p>There are no redactors in the service.</p>
  {% endif %}
{% endblock %}

templates/news/topic_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete topic?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="{% url 'news:topic-list' %}" class="btn btn-secondary">Cansel</a>
  </form>
{% endblock %}

templates/news/topic_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} topic</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/news/topic_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Topic List
    <a href="{% url 'news:topic-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>

  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" value="Submit" class="btn btn-secondary">
  </form>

  {% if topic_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>

      {% for topic in topic_list %}
        <tr>
          <td>
            {{ topic.id }}
          </td>
          <td>
            {{ topic.name }}
          </td>
          <td>
            <a href="{% url 'news:topic-update' pk=topic.id %}">
              Update
            </a>
          </td>
          <td>
            <a href="{% url 'news:topic-delete' pk=topic.id %}" style="color: red">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>

  {% else %}
    <p>There are no topic in the base.</p>
  {% endif %}
{% endblock %}